
CreateUser= https://petstore.swagger.io/v2/user
GetUser= https://petstore.swagger.io/v2/user/{username}
UpdateUser= https://petstore.swagger.io/v2/user/{username}
DeleteUser= https://petstore.swagger.io/v2/user/{username}